---
abstract: 'RT Extension-DateTAI64 Extension'
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-DateTAI64
no_index:
  directory:
    - inc
requires:
  Time::TAI64: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
